spring:
  datasource:
#    jndi-name: jndi/demo
    #this needs to be a shared database, we're deploying this in a cluster
    url: jdbc:oracle:thin:@localhost:49161:xe
    username: system
    password: oracle
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        proc:
          param_null_passing: true
