spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:49161:xe
    username: system
    password: oracle
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

logging:
  level:
    org.hibernate.SQL: DEBUG


